CREATE OR REPLACE TABLE average_sales_price_new_cleaned as
SELECT
    MONTH,
    YEAR,
    REGION,

    CAST(REPLACE(ZERO, '$', '') AS NUMBER) AS ZERO_BEDROOM,
    CAST(REPLACE(ONE, '$', '') AS NUMBER) AS ONE_BEDROOM,
    CAST(REPLACE(TWO, '$', '') AS NUMBER) AS TWO_BEDROOM,
    CAST(REPLACE(THREE, '$', '') AS NUMBER) AS THREE_BEDROOM,
    CAST(REPLACE(FOUR, '$', '') AS NUMBER) AS FOUR_BEDROOM,
    CAST(REPLACE(FIVE_AND_PLUS, '$', '') AS NUMBER) AS FIVE_PLUS_BEDROOM

FROM average_sales_price_new;
